var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/chat-compassionate/route.js")
R.c("server/chunks/26d59_next_de0e3a7e._.js")
R.c("server/chunks/26d59_@opentelemetry_api_build_esm_fdab1fec._.js")
R.c("server/chunks/26d59_openai_b15a005a._.js")
R.c("server/chunks/26d59_@supabase_auth-js_dist_module_b5d26d80._.js")
R.c("server/chunks/26d59_d37139a3._.js")
R.c("server/chunks/[root-of-the-server]__1fe8c1d9._.js")
R.c("server/chunks/e2c0f__next-internal_server_app_api_chat-compassionate_route_actions_fb9684c5.js")
R.m("[project]/Documents/Antigravity/ProjectProfound/profound-archive/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Documents/Antigravity/ProjectProfound/profound-archive/src/app/api/chat-compassionate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/Documents/Antigravity/ProjectProfound/profound-archive/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Documents/Antigravity/ProjectProfound/profound-archive/src/app/api/chat-compassionate/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
