/**
 * YouTube Subtitle/Caption Fetcher (Apify-powered)
 * 
 * Fetches timestamped captions from YouTube via Apify's YouTube Transcript
 * Scraper actor. This replaced the previous direct-scraping approach because
 * YouTube blocked server-side access to the timedtext XML endpoint in 2025.
 * 
 * Why Apify: YouTube's timedtext API returns empty responses for all 
 * server-side requests (Node.js fetch, https.get, etc.). Apify actors run
 * in real browser environments that bypass this restriction.
 * 
 * Actor: pintostudio/youtube-transcript-scraper
 * 
 * Strategy: async polling instead of a single long-poll HTTP connection.
 * The waitForFinish=N approach keeps one HTTP connection open for N seconds,
 * which is fragile under Firebase/serverless timeouts. Instead we:
 * 1. Start the run (non-blocking)
 * 2. Poll the run status every 5s until SUCCEEDED or FAILED
 * 3. Fetch the dataset
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CaptionSegment {
    text: string;
    start: number;   // Start time in seconds
    duration: number; // Duration in seconds
}

export interface CaptionResult {
    segments: CaptionSegment[];
    language: string;
    isAutoGenerated: boolean;
}

// ─── Apify Configuration ────────────────────────────────────────────────────

const APIFY_ACTOR_ID = 'pintostudio~youtube-transcript-scraper';
const APIFY_BASE_URL = 'https://api.apify.com/v2';

/** Maximum total seconds to wait for the actor to complete */
const APIFY_MAX_WAIT_SECS = 100;
/** Polling interval in milliseconds */
const APIFY_POLL_INTERVAL_MS = 5000;

// ─── Caption Fetching ────────────────────────────────────────────────────────

/**
 * Fetch timestamped captions for a YouTube video via Apify.
 * 
 * Uses async polling (start run → poll every 5s) to avoid keeping a single
 * long-lived HTTP connection open, which is fragile on serverless platforms.
 * 
 * @returns CaptionResult with segments, or null if no captions available
 */
export async function fetchCaptions(videoId: string): Promise<CaptionResult | null> {
    const apiToken = process.env.APIFY_API_TOKEN;
    if (!apiToken) {
        console.error('Missing APIFY_API_TOKEN environment variable');
        return null;
    }

    try {
        const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
        console.log(`[Apify] Starting transcript fetch for ${videoId}...`);

        // Step 1: Start the actor run (non-blocking — do NOT wait for finish here)
        const startRes = await fetchWithTimeout(
            `${APIFY_BASE_URL}/acts/${APIFY_ACTOR_ID}/runs`,
            {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${apiToken}`,
                },
                body: JSON.stringify({ videoUrl }),
            },
            15000, // 15s to start the run — if this fails, it's a real API error
        );

        if (!startRes.ok) {
            const errorBody = await startRes.text();
            console.error(`[Apify] Failed to start actor run (${startRes.status}):`, errorBody);
            return null;
        }

        const startData = await startRes.json();
        const runId = startData?.data?.id;
        if (!runId) {
            console.error('[Apify] No run ID returned from actor start');
            return null;
        }

        console.log(`[Apify] Run started: ${runId} — polling for completion...`);

        // Step 2: Poll the run status until SUCCEEDED, FAILED, or timeout
        const deadline = Date.now() + APIFY_MAX_WAIT_SECS * 1000;
        let runStatus: string = 'RUNNING';
        let datasetId: string | null = null;

        while (Date.now() < deadline) {
            await sleep(APIFY_POLL_INTERVAL_MS);

            const statusRes = await fetchWithTimeout(
                `${APIFY_BASE_URL}/actor-runs/${runId}`,
                { headers: { 'Authorization': `Bearer ${apiToken}` } },
                10000,
            );

            if (!statusRes.ok) {
                console.warn(`[Apify] Status poll failed (${statusRes.status}), retrying...`);
                continue;
            }

            const statusData = await statusRes.json();
            runStatus = statusData?.data?.status || 'UNKNOWN';
            datasetId = statusData?.data?.defaultDatasetId || null;

            console.log(`[Apify] Run ${runId} status: ${runStatus}`);

            if (runStatus === 'SUCCEEDED' || runStatus === 'FAILED' || runStatus === 'ABORTED' || runStatus === 'TIMED-OUT') {
                break;
            }
        }

        if (runStatus !== 'SUCCEEDED') {
            console.error(`[Apify] Actor run did not succeed. Final status: ${runStatus} (runId: ${runId})`);
            return null;
        }

        if (!datasetId) {
            console.error('[Apify] No dataset ID from completed run');
            return null;
        }

        // Step 3: Fetch results from the dataset
        const datasetRes = await fetchWithTimeout(
            `${APIFY_BASE_URL}/datasets/${datasetId}/items?format=json`,
            { headers: { 'Authorization': `Bearer ${apiToken}` } },
            15000,
        );

        if (!datasetRes.ok) {
            console.error(`[Apify] Failed to fetch dataset (${datasetRes.status})`);
            return null;
        }

        const items = await datasetRes.json();

        // Step 4: Extract transcript segments from the response
        const segments = extractSegments(items);

        if (segments.length === 0) {
            console.log(`[Apify] No transcript segments found for ${videoId} (dataset had ${items?.length ?? 0} items)`);
            // Log the raw first item for debugging so we can catch new response shapes
            if (items?.length > 0) {
                console.log(`[Apify] First item keys: ${Object.keys(items[0]).join(', ')}`);
            }
            return null;
        }

        console.log(`[Apify] Successfully fetched ${segments.length} segments for ${videoId}`);

        return {
            segments,
            language: 'en', // Actor defaults to English
            isAutoGenerated: true,
        };
    } catch (error: any) {
        console.error(`[Apify] Error fetching captions for ${videoId}:`, error?.message || error);
        return null;
    }
}

// ─── Internal Helpers ────────────────────────────────────────────────────────

/**
 * fetch() with an explicit AbortController timeout.
 * Prevents connections from hanging indefinitely on serverless platforms.
 */
async function fetchWithTimeout(url: string, options: RequestInit, timeoutMs: number): Promise<Response> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    try {
        return await fetch(url, { ...options, signal: controller.signal });
    } finally {
        clearTimeout(timer);
    }
}

function sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Extract CaptionSegment[] from Apify dataset items.
 * 
 * The Pinto Studio actor returns data in this format:
 * [{ data: [{ start: "0.320", dur: "4.080", text: "..." }, ...] }]
 * 
 * We also handle potential variations in the response shape.
 */
function extractSegments(items: any[]): CaptionSegment[] {
    if (!items || !Array.isArray(items) || items.length === 0) {
        return [];
    }

    const segments: CaptionSegment[] = [];

    for (const item of items) {
        // Known formats from pintostudio actor (data is the confirmed primary key)
        const results = item.data || item.searchResult || item.transcript || item.captions || item.subtitles || [];

        if (Array.isArray(results)) {
            for (const entry of results) {
                const start = parseFloat(entry.start);
                const duration = parseFloat(entry.dur || entry.duration || '0');
                const text = decodeHtmlEntities((entry.text || '').trim());

                if (text && !isNaN(start)) {
                    segments.push({ text, start, duration: isNaN(duration) ? 0 : duration });
                }
            }
        }
    }

    return segments;
}

/**
 * Decode common HTML entities found in YouTube caption text.
 */
function decodeHtmlEntities(text: string): string {
    return text
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&apos;/g, "'")
        .replace(/\n/g, ' ')
        .trim();
}
