/**
 * YouTube Subtitle/Caption Fetcher (Supadata-powered)
 *
 * Fetches timestamped captions from YouTube via Supadata's transcript API.
 *
 * Why Supadata (replaces Apify pintostudio actor):
 * The pintostudio Apify actor was IP-blocked by YouTube — it would return
 * a SUCCEEDED run with `{ data: [] }` (empty) for videos that actually have
 * captions. Supadata uses its own rotating proxy infrastructure that YouTube
 * does not block, returning full transcripts consistently.
 *
 * API: https://api.supadata.ai/v1/youtube/transcript?videoId=XXX
 * Auth: x-api-key header
 * Response: { lang, availableLangs, content: [{ text, offset, duration }] }
 *   - offset and duration are in MILLISECONDS
 *
 * Pricing: 1 credit per transcript, 100 free/month, $10 per 1,000 extra (~$0.01/video)
 * Docs: https://docs.supadata.ai
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CaptionSegment {
    text: string;
    start: number;    // Start time in seconds
    duration: number; // Duration in seconds
}

export interface CaptionResult {
    segments: CaptionSegment[];
    language: string;
    isAutoGenerated: boolean;
}

// ─── Caption Fetching ─────────────────────────────────────────────────────────

/**
 * Fetch timestamped captions for a YouTube video via Supadata.
 *
 * Single HTTP call — no polling, no actor warm-up delays.
 * Typical response time: 3–7 seconds.
 *
 * @returns CaptionResult with segments, or null if no captions available
 */
export async function fetchCaptions(videoId: string): Promise<CaptionResult | null> {
    const apiKey = process.env.SUPADATA_API_KEY;
    if (!apiKey) {
        console.error('[Supadata] Missing SUPADATA_API_KEY environment variable');
        return null;
    }

    const url = `https://api.supadata.ai/v1/youtube/transcript?videoId=${videoId}`;
    console.log(`[Supadata] Fetching transcript for ${videoId}...`);

    try {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), 30000); // 30s timeout

        let res: Response;
        try {
            res = await fetch(url, {
                headers: { 'x-api-key': apiKey },
                signal: controller.signal,
            });
        } finally {
            clearTimeout(timer);
        }

        if (!res.ok && res.status !== 206) {
            const body = await res.text();
            if (res.status === 401) {
                console.error(`[Supadata] INVALID API KEY (401) for ${videoId} — check SUPADATA_API_KEY environment variable.`);
            } else if (res.status === 402) {
                console.error(`[Supadata] PAYMENT REQUIRED (402) for ${videoId} — monthly credits exhausted. Add credits at https://dash.supadata.ai`);
            } else if (res.status === 429) {
                console.error(`[Supadata] RATE LIMITED (429) for ${videoId} — request rate exceeded. Response: ${body}`);
            } else if (res.status === 404) {
                console.log(`[Supadata] No captions available for ${videoId} (404)`);
            } else if (res.status >= 500) {
                console.error(`[Supadata] SERVER ERROR (${res.status}) for ${videoId} — Supadata infrastructure issue. Response: ${body}`);
            } else {
                console.error(`[Supadata] HTTP ${res.status} for ${videoId}: ${body}`);
            }
            return null;
        }

        // 206 = Supadata's "transcript-unavailable" — video exists but has no captions
        if (res.status === 206) {
            console.log(`[Supadata] Transcript unavailable for ${videoId} (206) — video has no captions.`);
            return null;
        }

        // Read body as text first — if Supadata's CDN returns an HTML error page with
        // a 200 status, res.json() would throw an ugly "Unexpected token '<'" error.
        const rawBody = await res.text();
        let data: { lang: string; availableLangs: string[]; content: Array<{ text: string; offset: number; duration: number; lang: string }> };
        try {
            data = JSON.parse(rawBody);
        } catch {
            console.error(`[Supadata] Non-JSON response for ${videoId} (HTTP ${res.status}): ${rawBody.slice(0, 150).replace(/\s+/g, ' ')}`);
            return null;
        }

        const content = data?.content;
        if (!Array.isArray(content) || content.length === 0) {
            console.log(`[Supadata] No transcript content for ${videoId} (lang: ${data?.lang})`);
            return null;
        }

        // Supadata returns offset + duration in milliseconds — convert to seconds
        const segments: CaptionSegment[] = content
            .map(seg => ({
                text: decodeHtmlEntities((seg.text || '').trim()),
                start: (seg.offset ?? 0) / 1000,
                duration: (seg.duration ?? 0) / 1000,
            }))
            .filter(seg => seg.text.length > 0);

        console.log(`[Supadata] ✅ ${segments.length} segments for ${videoId} (lang: ${data.lang})`);

        return {
            segments,
            language: data.lang || 'en',
            isAutoGenerated: true, // Supadata doesn't distinguish; assume auto
        };
    } catch (error: any) {
        if (error?.name === 'AbortError') {
            console.error(`[Supadata] Timeout (30s) fetching captions for ${videoId}`);
        } else {
            console.error(`[Supadata] Error fetching captions for ${videoId}:`, error?.message || error);
        }
        return null;
    }
}

// ─── Internal Helpers ─────────────────────────────────────────────────────────

/**
 * Decode common HTML entities found in YouTube caption text.
 */
function decodeHtmlEntities(text: string): string {
    return text
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&apos;/g, "'")
        .replace(/\n/g, ' ')
        .trim();
}
