/**
 * YouTube Subtitle/Caption Fetcher (Apify-powered)
 * 
 * Fetches timestamped captions from YouTube via Apify's YouTube Transcript
 * Scraper actor. This replaced the previous direct-scraping approach because
 * YouTube blocked server-side access to the timedtext XML endpoint in 2025.
 * 
 * Why Apify: YouTube's timedtext API returns empty responses for all 
 * server-side requests (Node.js fetch, https.get, etc.). Apify actors run
 * in real browser environments that bypass this restriction.
 * 
 * Actor: pintostudio/youtube-transcript-scraper
 * Pricing: ~$0.005 per run on Apify free tier (100 runs/month)
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CaptionSegment {
    text: string;
    start: number;   // Start time in seconds
    duration: number; // Duration in seconds
}

export interface CaptionResult {
    segments: CaptionSegment[];
    language: string;
    isAutoGenerated: boolean;
}

// ─── Apify Configuration ────────────────────────────────────────────────────

const APIFY_ACTOR_ID = 'pintostudio~youtube-transcript-scraper';
const APIFY_BASE_URL = 'https://api.apify.com/v2';
const APIFY_TIMEOUT_SECS = 120; // Max wait for actor run

// ─── Caption Fetching ────────────────────────────────────────────────────────

/**
 * Fetch timestamped captions for a YouTube video via Apify.
 * 
 * Strategy:
 * 1. Call Apify's YouTube Transcript Scraper actor with the video URL
 * 2. Wait for the actor run to complete (synchronous mode)
 * 3. Fetch results from the default dataset
 * 4. Map Apify's output to our CaptionSegment format
 * 
 * @returns CaptionResult with segments, or null if no captions available
 */
export async function fetchCaptions(videoId: string): Promise<CaptionResult | null> {
    const apiToken = process.env.APIFY_API_TOKEN;
    if (!apiToken) {
        console.error('Missing APIFY_API_TOKEN environment variable');
        return null;
    }

    try {
        // Step 1: Start the actor run (synchronous — waits for completion)
        const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
        console.log(`[Apify] Starting transcript fetch for ${videoId}...`);

        const runResponse = await fetch(
            `${APIFY_BASE_URL}/acts/${APIFY_ACTOR_ID}/runs?waitForFinish=${APIFY_TIMEOUT_SECS}`,
            {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${apiToken}`,
                },
                body: JSON.stringify({ videoUrl }),
            }
        );

        if (!runResponse.ok) {
            const errorBody = await runResponse.text();
            console.error(`[Apify] Actor run failed (${runResponse.status}):`, errorBody);
            return null;
        }

        const runData = await runResponse.json();
        const runStatus = runData?.data?.status;
        const datasetId = runData?.data?.defaultDatasetId;

        if (runStatus !== 'SUCCEEDED') {
            console.error(`[Apify] Actor run did not succeed. Status: ${runStatus}`);
            return null;
        }

        if (!datasetId) {
            console.error('[Apify] No dataset ID returned from actor run');
            return null;
        }

        // Step 2: Fetch results from the dataset
        const datasetResponse = await fetch(
            `${APIFY_BASE_URL}/datasets/${datasetId}/items?format=json`,
            {
                headers: {
                    'Authorization': `Bearer ${apiToken}`,
                },
            }
        );

        if (!datasetResponse.ok) {
            console.error(`[Apify] Failed to fetch dataset (${datasetResponse.status})`);
            return null;
        }

        const items = await datasetResponse.json();

        // Step 3: Extract transcript segments from the response
        // The actor returns items with a searchResult array
        const segments = extractSegments(items);

        if (segments.length === 0) {
            console.log(`[Apify] No transcript segments found for ${videoId}`);
            return null;
        }

        console.log(`[Apify] Successfully fetched ${segments.length} segments for ${videoId}`);

        return {
            segments,
            language: 'en', // Actor defaults to English
            isAutoGenerated: true, // Conservative assumption
        };
    } catch (error) {
        console.error(`[Apify] Error fetching captions for ${videoId}:`, error);
        return null;
    }
}

// ─── Internal Helpers ────────────────────────────────────────────────────────

/**
 * Extract CaptionSegment[] from Apify dataset items.
 * 
 * The Pinto Studio actor returns data in this format:
 * [{ searchResult: [{ start: "0.320", dur: "4.080", text: "..." }, ...] }]
 * 
 * We also handle potential variations in the response shape.
 */
function extractSegments(items: any[]): CaptionSegment[] {
    if (!items || !Array.isArray(items) || items.length === 0) {
        return [];
    }

    const segments: CaptionSegment[] = [];

    for (const item of items) {
        // Primary format: { data: [...] } (confirmed from pintostudio actor)
        // Also handle alternate formats: { searchResult: [...] }, { transcript: [...] }
        const results = item.data || item.searchResult || item.transcript || item.captions || [];

        if (Array.isArray(results)) {
            for (const entry of results) {
                const start = parseFloat(entry.start);
                const duration = parseFloat(entry.dur || entry.duration || '0');
                const text = decodeHtmlEntities((entry.text || '').trim());

                if (text && !isNaN(start)) {
                    segments.push({ text, start, duration: isNaN(duration) ? 0 : duration });
                }
            }
        }
    }

    return segments;
}

/**
 * Decode common HTML entities found in YouTube caption text.
 */
function decodeHtmlEntities(text: string): string {
    return text
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&apos;/g, "'")
        .replace(/\n/g, ' ')
        .trim();
}
