var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/chat-compassionate/route.js")
R.c("server/chunks/[root-of-the-server]__07abc09d._.js")
R.c("server/chunks/26d59_openai_index_mjs_a45c1652._.js")
R.c("server/chunks/26d59_next_dist_esm_build_templates_app-route_829c11ed.js")
R.c("server/chunks/26d59_@supabase_supabase-js_dist_index_mjs_14c76eff._.js")
R.c("server/chunks/[root-of-the-server]__c35e3fce._.js")
R.c("server/chunks/26d59_ff1f28ad._.js")
R.c("server/chunks/e2c0f__next-internal_server_app_api_chat-compassionate_route_actions_fb9684c5.js")
R.m(59433)
module.exports=R.m(59433).exports
