// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/chatbot" | "/admin/intake" | "/admin/users" | "/channel/[channelId]" | "/channels" | "/chat" | "/chat-2" | "/chat-compassionate" | "/chat-test" | "/dashboard" | "/experiencers" | "/explore/greyson" | "/explore/transformation" | "/explore/veridical" | "/login" | "/privacy" | "/profile" | "/resources" | "/scale/cvnde" | "/scale/greyson" | "/scale/transformation" | "/search" | "/search2" | "/search3" | "/search3/dev/v4" | "/terms" | "/video/[id]"
type AppRouteHandlerRoutes = "/api/batch/run-fingerprint-batch" | "/api/chat" | "/api/chat-compassionate" | "/api/intake" | "/api/run-core-elements-batch" | "/api/run-greyson-batch" | "/api/run-journey-flow-batch" | "/api/run-phenomenology-batch" | "/api/run-transformation-batch" | "/api/search" | "/api/search2" | "/api/search3" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/chatbot": {}
  "/admin/intake": {}
  "/admin/users": {}
  "/api/batch/run-fingerprint-batch": {}
  "/api/chat": {}
  "/api/chat-compassionate": {}
  "/api/intake": {}
  "/api/run-core-elements-batch": {}
  "/api/run-greyson-batch": {}
  "/api/run-journey-flow-batch": {}
  "/api/run-phenomenology-batch": {}
  "/api/run-transformation-batch": {}
  "/api/search": {}
  "/api/search2": {}
  "/api/search3": {}
  "/auth/callback": {}
  "/channel/[channelId]": { "channelId": string; }
  "/channels": {}
  "/chat": {}
  "/chat-2": {}
  "/chat-compassionate": {}
  "/chat-test": {}
  "/dashboard": {}
  "/experiencers": {}
  "/explore/greyson": {}
  "/explore/transformation": {}
  "/explore/veridical": {}
  "/login": {}
  "/privacy": {}
  "/profile": {}
  "/resources": {}
  "/scale/cvnde": {}
  "/scale/greyson": {}
  "/scale/transformation": {}
  "/search": {}
  "/search2": {}
  "/search3": {}
  "/search3/dev/v4": {}
  "/terms": {}
  "/video/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
