export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <div className="bg-white rounded-lg shadow-md p-8">
        <h1 className="text-4xl font-extrabold text-foreground mb-4">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last Updated: September 25, 2025</p>
        <div className="prose prose-lg max-w-none space-y-6 text-muted-foreground">
          <p>
            Please read these Terms of Service (&quot;Terms&quot;) carefully before using Project Profound
            website (the &quot;Website&quot;) and its services (the &quot;Services&quot;). Your access to and use
            of the Service is conditioned on your acceptance of and compliance with these Terms. These
            Terms apply to all visitors, users, and others who access or use the Service.
          </p>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Service, you agree to be bound by these Terms. If you disagree
              with any part of the terms, then you may not access the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">2. Description of Service</h2>
            <p>
              Project Profound provides tools for NDE (Near-Death Experience) research, including a video
              search engine and AI-powered analysis tools. The Services are provided for informational,
              educational, and research purposes only. The analyses and scores (e.g., Greyson Scale) are
              generated by AI models and are intended as research tools, not as definitive or clinical
              assessments.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">3. Use of Data and Research</h2>
            <p>
              By using our research tools (such as the &quot;NDE Video Researcher&quot; or &quot;AI Analysis
              of NDE Testimonies&quot;), you grant Project Profound a perpetual, irrevocable, worldwide,
              royalty-free, and non-exclusive license to use, reproduce, adapt, modify, and publish the
              anonymized data you submit (e.g., search terms, YouTube URLs) for the purpose of research,
              training our AI models, and advancing the public understanding of NDEs.
            </p>
            <p>
              You agree that you will not submit any personally identifiable information (other than in the
              designated contact forms) or any content that infringes on the rights of any third party.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">4. Prohibited Conduct</h2>
            <p>
              You agree not to use the Service for any purpose that is illegal or prohibited by these Terms.
              You agree not to:
            </p>
            <ul className="list-disc list-inside">
              <li>Use the Service to harass, abuse, or threaten others.</li>
              <li>Submit any content that is defamatory, obscene, or offensive.</li>
              <li>
                Attempt to gain unauthorized access to our computer systems or engage in any activity that
                disrupts, diminishes the quality of, interferes with the performance of, or impairs the
                functionality of the Service.
              </li>
              <li>
                Use any automated system, including without limitation &quot;robots,&quot; &quot;spiders,&quot; or &quot;offline
                readers,&quot; to access the Service in a manner that sends more request messages to our
                servers than a human can reasonably produce in the same period by using a conventional
                on-line web browser.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">5. Disclaimer of Warranties</h2>
            <p>
              The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. Project Profound
              makes no representations or warranties of any kind, express or implied, as to the operation
              of their services, or the information, content, or materials included therein. You expressly
              agree that your use of these services is at your sole risk.
            </p>
            <p>
              We do not warrant that the results obtained from the use of the Service will be accurate,
              reliable, or suitable for any specific purpose. The AI-generated content is for research and
              informational purposes and should not be considered a substitute for professional, clinical,
              or academic advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">6. Limitation of Liability</h2>
            <p>
              In no event shall Project Profound, its founders, volunteers, or affiliates be liable for any
              direct, indirect, incidental, special, consequential, or punitive damages arising out of your
              use of, or inability to use, the Service. This includes, but is not limited to, damages for
              loss of profits, data, or other intangibles.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">7. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless Project Profound and its affiliates from and against
              any and all claims, liabilities, damages, losses, or expenses, including reasonable
              attorneys&apos; fees and costs, arising out of or in any way connected with your access to or use
              of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">8. Changes to These Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We
              will provide notice of any changes by posting the new Terms of Service on this page and
              updating the &quot;Last Updated&quot; date. Your continued use of the Service after any such
              changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">9. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the jurisdiction in
              which Project Profound operates, without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-3">10. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us through the form on our
              contact page.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
