var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/intake/route.js")
R.c("server/chunks/[root-of-the-server]__c8d80690._.js")
R.c("server/chunks/26d59_next_d951faa0._.js")
R.c("server/chunks/26d59_@opentelemetry_api_build_esm_fdab1fec._.js")
R.c("server/chunks/d665f_@supabase_realtime-js_dist_module_76ef3b00._.js")
R.c("server/chunks/d665f_@supabase_auth-js_dist_module_98e0f9c5._.js")
R.c("server/chunks/26d59_openai_b15a005a._.js")
R.c("server/chunks/26d59_typesense_lib_63dac012._.js")
R.c("server/chunks/26d59_mime-db_37f5fa83._.js")
R.c("server/chunks/26d59_axios_dist_node_axios_cjs_870b389f._.js")
R.c("server/chunks/26d59_3c071502._.js")
R.c("server/chunks/a911d_profound-archive__next-internal_server_app_api_intake_route_actions_4dc08cc5.js")
R.m("[project]/Documents/Antigravity/ProjectProfound/profound-archive/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Documents/Antigravity/ProjectProfound/profound-archive/src/app/api/intake/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/Documents/Antigravity/ProjectProfound/profound-archive/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Documents/Antigravity/ProjectProfound/profound-archive/src/app/api/intake/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
