var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/search2/route.js")
R.c("server/chunks/node_modules_next_3e13bc12._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_7e8f41ca._.js")
R.c("server/chunks/node_modules_typesense_lib_a44ae15a._.js")
R.c("server/chunks/node_modules_mime-db_f53cdd2e._.js")
R.c("server/chunks/node_modules_axios_dist_node_axios_cjs_ef84af05._.js")
R.c("server/chunks/node_modules_08a945fd._.js")
R.c("server/chunks/[root-of-the-server]__c6dbed80._.js")
R.c("server/chunks/_next-internal_server_app_api_search2_route_actions_8b9e8ef3.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/search2/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/search2/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
